service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: {env:PG_HOST}
    PG_PORT: {env:PG_PORT}
    PG_DATABASE: {env:PG_DATABASE}
    PG_USERNAME: {env:PG_USERNAME}
    PG_PASSWORD: {env:PG_PASSWORD}

functions:
  getProductList:
    handler: index.getProductList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductById:
    handler: index.getProductById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  createProduct:
    handler: index.createProduct
    events:
      - http:
          path: /products
          method: post
          cors: true
custom:
    autoswagger:
      basePath: /dev
      generateSwaggerOnDeploy: true
      swaggerPath: swagger
      apiType: http