service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  getProductList:
    handler: index.getProductList
    events:
      - http:
          path: /products
          method: get
  getProductById:
    handler: index.getProductById
    events:
      - http:
          path: /products/{productId}
          method: get
